### ISSUE TITLE
phsyics

### ISSUE THREAD

**Issue by glennmichaelmejias** [MasahideMori1111/simple_3d#4]
does 3d physics supported such as collide?

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @glennmichaelmejias ,
Thanks for the question.

Collision detection is not defined in this package itself.
There are various cases depending on what kind of collision detection the user wants to use.
However, the easiest method has some support.
Sp3dObj.getCenter() gives the vector of object centers.
If you define the radius of each object and store it in the option variable, you can judge the collision from the vector of the center and radius of each object.

Calculate as follows.
1. Addition the radius of the two objects.
2. Get the center coordinates of the two objects with Sp3dObj.getCenter() and get the Euclidean distance with Sp3dV3D.dist().
3. If the result of 1 is greater than the result of 2, they are colliding.

**Comment by MasahideMori-SimpleAppli** [comment]
I will close this question for now. If your question is not answered, please open another question.
Thank you.

**Comment by glennmichaelmejias** [comment]
thanks for this, 3d physics simulation in flutter is really a great features to have.
