### ISSUE TITLE
Very impressed!

### ISSUE THREAD

**Issue by robelator** [MasahideMori1111/simple_3d#7]
Good day mate. I'm a programmer from Australia and I stumbled upon your package simple_3d and simple_3d_renderer. Just want to say that I'm very impressed with your work. Did you use linear algebra to map 3D space to a 2D canvas or something? I can't seem to figure out how you did this but it's very cool! I definitely plan to use this in future projects :)

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @robmllze ,
Thank you for contacting me! I'm very honored that you like my work.
Yes, I use linear algebra to map 3D space onto a 2D canvas.
I hope my work will be useful for your future projects.

There is a sample project that uses this package for 3D effects, so please check it out if you like.
The source code is open, so it may be useful.
https://pub.dev/packages/sakura_blizzard
https://github.com/MasahideMori-SimpleAppli/sakura_blizzard

If you have any questions or concerns, please feel free to open an issue.
Thanks!
